# This is a sample build configuration for Javascript.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:11.12

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - npm install --verbose
          - npm test --verbose
          - if [ $? -eq 0 ]; then
          - npm run deployable --verbose
          - bash <(curl -s https://codecov.io/bash)
          - scp -r deploy/last-build/* npawdev@web1-nl4.youbora.com:/home/npawdev/qa/catalog/v6/js
          - fi

  tags:
    '*':
      - step:
          script:
            - npm install --verbose
            - npm test --verbose
            - if [ $? -eq 0 ]; then
            - npm run deployable --verbose
            - bash <(curl -s https://codecov.io/bash)
            - scp -r deploy/version/* npawdev@web1-nl4.youbora.com:/home/npawdev/qa/catalog/v6/js
            - fi

  custom: # Pipelines that are triggered manually
    deploy-to-prod:
      - step:
          script:
            - npm install --verbose
            - npm test --verbose
            - if [ $? -eq 0 ]; then
            # Generate files
            - npm run deployable --verbose
            # S3
            - apt-get update
            - apt-get -y install awscli
            - mkdir ~/.aws
            - echo "[default]" >> ~/.aws/credentials
            - echo "aws_access_key_id="$AWS_ACCESS_KEY_ID >>  ~/.aws/credentials
            - echo "aws_secret_access_key="$AWS_SECRET_ACCESS_KEY >>  ~/.aws/credentials
            - echo "[default]" >> ~/.aws/config
            - echo "region="$AWS_DEFAULT_REGION >> ~/.aws/config
            - echo "output=json" >> ~/.aws/config
            - aws s3 cp deploy/prod/ s3://youbora-smartplugins/v6/js/ --recursive --acl=public-read
            # codecov
            - bash <(curl -s https://codecov.io/bash)
            # deploy PROD file to qa
            - scp -r deploy/prodfile/* npawdev@web1-nl4.youbora.com:/home/npawdev/qa/catalog/v6/js
            - fi
    npm-publish:
      - step:
          script:
            - npm install --verbose
            - npm test --verbose
            - if [ $? -eq 0 ]; then
            # npm publish
            - echo $NPM_TOKEN >> ~/.npmrc
            - npm run manifest --verbose
            - npm publish --verbose -f
            - fi
    deployment:
      - step:
         deployment: production
         script:
            - npm install --verbose
            - npm test --verbose
            - if [ $? -eq 0 ]; then
            # Generate files
            - npm run deployable --verbose
            # S3
            - apt-get update
            - apt-get -y install awscli
            - mkdir ~/.aws
            - echo "[default]" >> ~/.aws/credentials
            - echo "aws_access_key_id="$AWS_ACCESS_KEY_ID >>  ~/.aws/credentials
            - echo "aws_secret_access_key="$AWS_SECRET_ACCESS_KEY >>  ~/.aws/credentials
            - echo "[default]" >> ~/.aws/config
            - echo "region="$AWS_DEFAULT_REGION >> ~/.aws/config
            - echo "output=json" >> ~/.aws/config
            - aws s3 cp deploy/prod/ s3://youbora-smartplugins/v6/js/ --recursive --acl=public-read
            # codecov
            - bash <(curl -s https://codecov.io/bash)
            # deploy PROD file to qa
            - scp -r deploy/prodfile/* npawdev@web1-nl4.youbora.com:/home/npawdev/qa/catalog/v6/js
            # npm publish
            - echo $NPM_TOKEN >> ~/.npmrc
            - npm run manifest --verbose
            - npm publish --verbose -f
            - fi
